//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式码是由工具生成的。
//     执行階段版本:4.0.30319.42000
//
//     對這個档案所做的變更可能會造成错误的行为，而且如果重新生成程式码，
//     變更将會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMServer {
    using System;
    
    
    /// <summary>
    ///   用于查询當地语言化字串等的強类型資源类別。
    /// </summary>
    // 這個类別是自动生成的，是利用 StronglyTypedResourceBuilder
    // 类別透過 ResGen 或 Visual Studio 這类工具。
    // 若要加入或移除成员，请編輯您的 .ResX 档，然后重新执行 ResGen
    // (利用 /str 选項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DialogLoginResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogLoginResource() {
        }
        
        /// <summary>
        ///   传回這個类別使用的快取的 ResourceManager 执行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICMServer.DialogLoginResource", typeof(DialogLoginResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前执行緒的 CurrentUICulture 属性，對象是所有
        ///   使用這個強类型資源类別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查询类型 System.Drawing.Bitmap 的當地语言化資源。
        /// </summary>
        public static System.Drawing.Bitmap BtnCloseBackgroundImage {
            get {
                object obj = ResourceManager.GetObject("BtnCloseBackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查询类型 System.Drawing.Bitmap 的當地语言化資源。
        /// </summary>
        public static System.Drawing.Bitmap BtnCloseBackgroundImage2 {
            get {
                object obj = ResourceManager.GetObject("BtnCloseBackgroundImage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查询类型 System.Drawing.Bitmap 的當地语言化資源。
        /// </summary>
        public static System.Drawing.Bitmap BtnCloseClickedBackgroundImage {
            get {
                object obj = ResourceManager.GetObject("BtnCloseClickedBackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查询类型 System.Drawing.Bitmap 的當地语言化資源。
        /// </summary>
        public static System.Drawing.Bitmap BtnCloseClickedBackgroundImage2 {
            get {
                object obj = ResourceManager.GetObject("BtnCloseClickedBackgroundImage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查询类型 System.Drawing.Bitmap 的當地语言化資源。
        /// </summary>
        public static System.Drawing.Bitmap BtnLoginBackgroundImage {
            get {
                object obj = ResourceManager.GetObject("BtnLoginBackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查询类型 System.Drawing.Bitmap 的當地语言化資源。
        /// </summary>
        public static System.Drawing.Bitmap BtnLoginBackgroundImage2 {
            get {
                object obj = ResourceManager.GetObject("BtnLoginBackgroundImage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查询类型 System.Drawing.Bitmap 的當地语言化資源。
        /// </summary>
        public static System.Drawing.Bitmap BtnLoginClickedBackgroundImage {
            get {
                object obj = ResourceManager.GetObject("BtnLoginClickedBackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查询类型 System.Drawing.Bitmap 的當地语言化資源。
        /// </summary>
        public static System.Drawing.Bitmap BtnLoginClickedBackgroundImage2 {
            get {
                object obj = ResourceManager.GetObject("BtnLoginClickedBackgroundImage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查询类型 System.Drawing.Bitmap 的當地语言化資源。
        /// </summary>
        public static System.Drawing.Bitmap dlg_login_CHT {
            get {
                object obj = ResourceManager.GetObject("dlg_login_CHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查询类型 System.Drawing.Bitmap 的當地语言化資源。
        /// </summary>
        public static System.Drawing.Bitmap dlgLoginBackgroundImage {
            get {
                object obj = ResourceManager.GetObject("dlgLoginBackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
