//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMServer {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlaceName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlaceName() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICMServer.PlaceName", typeof(PlaceName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 阿壩 的本地化字符串。
        /// </summary>
        internal static string Aba {
            get {
                return ResourceManager.GetString("Aba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阿克蘇 的本地化字符串。
        /// </summary>
        internal static string Aksu {
            get {
                return ResourceManager.GetString("Aksu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阿里 的本地化字符串。
        /// </summary>
        internal static string Ali {
            get {
                return ResourceManager.GetString("Ali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阿勒泰 的本地化字符串。
        /// </summary>
        internal static string Altay {
            get {
                return ResourceManager.GetString("Altay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安徽 的本地化字符串。
        /// </summary>
        internal static string Anhui {
            get {
                return ResourceManager.GetString("Anhui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安康 的本地化字符串。
        /// </summary>
        internal static string Ankang {
            get {
                return ResourceManager.GetString("Ankang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安慶 的本地化字符串。
        /// </summary>
        internal static string Anqing {
            get {
                return ResourceManager.GetString("Anqing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鞍山 的本地化字符串。
        /// </summary>
        internal static string Anshan {
            get {
                return ResourceManager.GetString("Anshan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安順 的本地化字符串。
        /// </summary>
        internal static string Anshun {
            get {
                return ResourceManager.GetString("Anshun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安陽 的本地化字符串。
        /// </summary>
        internal static string Anyang {
            get {
                return ResourceManager.GetString("Anyang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 百色 的本地化字符串。
        /// </summary>
        internal static string Baise {
            get {
                return ResourceManager.GetString("Baise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保定 的本地化字符串。
        /// </summary>
        internal static string Baoding {
            get {
                return ResourceManager.GetString("Baoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寶雞 的本地化字符串。
        /// </summary>
        internal static string Baoji {
            get {
                return ResourceManager.GetString("Baoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保山 的本地化字符串。
        /// </summary>
        internal static string Baoshan {
            get {
                return ResourceManager.GetString("Baoshan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包頭 的本地化字符串。
        /// </summary>
        internal static string Baotou {
            get {
                return ResourceManager.GetString("Baotou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 北京 的本地化字符串。
        /// </summary>
        internal static string Beijing {
            get {
                return ResourceManager.GetString("Beijing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蚌埠 的本地化字符串。
        /// </summary>
        internal static string Bengbu {
            get {
                return ResourceManager.GetString("Bengbu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本溪 的本地化字符串。
        /// </summary>
        internal static string Benxi {
            get {
                return ResourceManager.GetString("Benxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 畢節 的本地化字符串。
        /// </summary>
        internal static string Bijie {
            get {
                return ResourceManager.GetString("Bijie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 濱州 的本地化字符串。
        /// </summary>
        internal static string Binzhou {
            get {
                return ResourceManager.GetString("Binzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 亳州 的本地化字符串。
        /// </summary>
        internal static string Bozhou {
            get {
                return ResourceManager.GetString("Bozhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 滄州 的本地化字符串。
        /// </summary>
        internal static string Cangzhou {
            get {
                return ResourceManager.GetString("Cangzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 凱里 的本地化字符串。
        /// </summary>
        internal static string Carey {
            get {
                return ResourceManager.GetString("Carey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 長春 的本地化字符串。
        /// </summary>
        internal static string Changchun {
            get {
                return ResourceManager.GetString("Changchun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常德 的本地化字符串。
        /// </summary>
        internal static string Changde {
            get {
                return ResourceManager.GetString("Changde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昌吉 的本地化字符串。
        /// </summary>
        internal static string Changji {
            get {
                return ResourceManager.GetString("Changji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 長沙 的本地化字符串。
        /// </summary>
        internal static string Changsha {
            get {
                return ResourceManager.GetString("Changsha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常熟 的本地化字符串。
        /// </summary>
        internal static string Changshu {
            get {
                return ResourceManager.GetString("Changshu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 長治 的本地化字符串。
        /// </summary>
        internal static string Changzhi {
            get {
                return ResourceManager.GetString("Changzhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常州 的本地化字符串。
        /// </summary>
        internal static string Changzhou {
            get {
                return ResourceManager.GetString("Changzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 朝陽 的本地化字符串。
        /// </summary>
        internal static string Chaoyang {
            get {
                return ResourceManager.GetString("Chaoyang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 潮州 的本地化字符串。
        /// </summary>
        internal static string Chaozhou {
            get {
                return ResourceManager.GetString("Chaozhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 承德 的本地化字符串。
        /// </summary>
        internal static string Chengde {
            get {
                return ResourceManager.GetString("Chengde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成都 的本地化字符串。
        /// </summary>
        internal static string Chengdu {
            get {
                return ResourceManager.GetString("Chengdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 郴州 的本地化字符串。
        /// </summary>
        internal static string Chenzhou {
            get {
                return ResourceManager.GetString("Chenzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 赤峰 的本地化字符串。
        /// </summary>
        internal static string Chifeng {
            get {
                return ResourceManager.GetString("Chifeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 赤水 的本地化字符串。
        /// </summary>
        internal static string Chishui {
            get {
                return ResourceManager.GetString("Chishui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 池州 的本地化字符串。
        /// </summary>
        internal static string Chizhou {
            get {
                return ResourceManager.GetString("Chizhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重慶 的本地化字符串。
        /// </summary>
        internal static string Chongqing {
            get {
                return ResourceManager.GetString("Chongqing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 崇左 的本地化字符串。
        /// </summary>
        internal static string Chongzuo {
            get {
                return ResourceManager.GetString("Chongzuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 楚雄 的本地化字符串。
        /// </summary>
        internal static string Chuxiong {
            get {
                return ResourceManager.GetString("Chuxiong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 滁州 的本地化字符串。
        /// </summary>
        internal static string Chuzhou {
            get {
                return ResourceManager.GetString("Chuzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大安 的本地化字符串。
        /// </summary>
        internal static string Daan {
            get {
                return ResourceManager.GetString("Daan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大理 的本地化字符串。
        /// </summary>
        internal static string Dali {
            get {
                return ResourceManager.GetString("Dali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大连 的本地化字符串。
        /// </summary>
        internal static string Dalian {
            get {
                return ResourceManager.GetString("Dalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 丹東 的本地化字符串。
        /// </summary>
        internal static string Dandong {
            get {
                return ResourceManager.GetString("Dandong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 儋州 的本地化字符串。
        /// </summary>
        internal static string Danzhou {
            get {
                return ResourceManager.GetString("Danzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大慶 的本地化字符串。
        /// </summary>
        internal static string Daqing {
            get {
                return ResourceManager.GetString("Daqing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大同 的本地化字符串。
        /// </summary>
        internal static string Datong {
            get {
                return ResourceManager.GetString("Datong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大興安嶺 的本地化字符串。
        /// </summary>
        internal static string Daxinganling {
            get {
                return ResourceManager.GetString("Daxinganling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 達州 的本地化字符串。
        /// </summary>
        internal static string Dazhou {
            get {
                return ResourceManager.GetString("Dazhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中衛 的本地化字符串。
        /// </summary>
        internal static string Defender {
            get {
                return ResourceManager.GetString("Defender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 德宏 的本地化字符串。
        /// </summary>
        internal static string Dehong {
            get {
                return ResourceManager.GetString("Dehong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 德慶 的本地化字符串。
        /// </summary>
        internal static string Deqing {
            get {
                return ResourceManager.GetString("Deqing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 德陽 的本地化字符串。
        /// </summary>
        internal static string Deyang {
            get {
                return ResourceManager.GetString("Deyang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定西 的本地化字符串。
        /// </summary>
        internal static string Dingxi {
            get {
                return ResourceManager.GetString("Dingxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 東莞 的本地化字符串。
        /// </summary>
        internal static string Dongguan {
            get {
                return ResourceManager.GetString("Dongguan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 東營 的本地化字符串。
        /// </summary>
        internal static string Dongying {
            get {
                return ResourceManager.GetString("Dongying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 都勻 的本地化字符串。
        /// </summary>
        internal static string Duyun {
            get {
                return ResourceManager.GetString("Duyun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恩施 的本地化字符串。
        /// </summary>
        internal static string Enshi {
            get {
                return ResourceManager.GetString("Enshi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鄂州 的本地化字符串。
        /// </summary>
        internal static string Ezhou {
            get {
                return ResourceManager.GetString("Ezhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 防城港 的本地化字符串。
        /// </summary>
        internal static string Fangchenggang {
            get {
                return ResourceManager.GetString("Fangchenggang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 福建 的本地化字符串。
        /// </summary>
        internal static string Fujian {
            get {
                return ResourceManager.GetString("Fujian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撫順 的本地化字符串。
        /// </summary>
        internal static string Fushun {
            get {
                return ResourceManager.GetString("Fushun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阜新 的本地化字符串。
        /// </summary>
        internal static string Fuxin {
            get {
                return ResourceManager.GetString("Fuxin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阜陽 的本地化字符串。
        /// </summary>
        internal static string Fuyang {
            get {
                return ResourceManager.GetString("Fuyang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撫州 的本地化字符串。
        /// </summary>
        internal static string Fuzhou {
            get {
                return ResourceManager.GetString("Fuzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 福州 的本地化字符串。
        /// </summary>
        internal static string Fuzhou2 {
            get {
                return ResourceManager.GetString("Fuzhou2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 甘南 的本地化字符串。
        /// </summary>
        internal static string Gannan {
            get {
                return ResourceManager.GetString("Gannan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 甘肅 的本地化字符串。
        /// </summary>
        internal static string Gansu {
            get {
                return ResourceManager.GetString("Gansu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 贛州 的本地化字符串。
        /// </summary>
        internal static string Ganzhou {
            get {
                return ResourceManager.GetString("Ganzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 甘孜州 的本地化字符串。
        /// </summary>
        internal static string GanziPrefecture {
            get {
                return ResourceManager.GetString("GanziPrefecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吉安 的本地化字符串。
        /// </summary>
        internal static string Gian {
            get {
                return ResourceManager.GetString("Gian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 廣安 的本地化字符串。
        /// </summary>
        internal static string Guangan {
            get {
                return ResourceManager.GetString("Guangan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 廣東 的本地化字符串。
        /// </summary>
        internal static string Guangdong {
            get {
                return ResourceManager.GetString("Guangdong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 廣西 的本地化字符串。
        /// </summary>
        internal static string Guangxi {
            get {
                return ResourceManager.GetString("Guangxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 廣元 的本地化字符串。
        /// </summary>
        internal static string Guangyuan {
            get {
                return ResourceManager.GetString("Guangyuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 廣州 的本地化字符串。
        /// </summary>
        internal static string Guangzhou {
            get {
                return ResourceManager.GetString("Guangzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 來賓 的本地化字符串。
        /// </summary>
        internal static string guest {
            get {
                return ResourceManager.GetString("guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 貴港 的本地化字符串。
        /// </summary>
        internal static string Guigang {
            get {
                return ResourceManager.GetString("Guigang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桂林 的本地化字符串。
        /// </summary>
        internal static string Guilin {
            get {
                return ResourceManager.GetString("Guilin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桂平 的本地化字符串。
        /// </summary>
        internal static string Guiping {
            get {
                return ResourceManager.GetString("Guiping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 貴陽 的本地化字符串。
        /// </summary>
        internal static string Guiyang {
            get {
                return ResourceManager.GetString("Guiyang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 貴州 的本地化字符串。
        /// </summary>
        internal static string Guizhou {
            get {
                return ResourceManager.GetString("Guizhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 果洛 的本地化字符串。
        /// </summary>
        internal static string Guoluo {
            get {
                return ResourceManager.GetString("Guoluo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 固原 的本地化字符串。
        /// </summary>
        internal static string Guyuan {
            get {
                return ResourceManager.GetString("Guyuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 海北 的本地化字符串。
        /// </summary>
        internal static string Haibei {
            get {
                return ResourceManager.GetString("Haibei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 海東 的本地化字符串。
        /// </summary>
        internal static string Haidong {
            get {
                return ResourceManager.GetString("Haidong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 海口 的本地化字符串。
        /// </summary>
        internal static string Haikou {
            get {
                return ResourceManager.GetString("Haikou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 海拉爾 的本地化字符串。
        /// </summary>
        internal static string Hailar {
            get {
                return ResourceManager.GetString("Hailar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 海南 的本地化字符串。
        /// </summary>
        internal static string Hainan {
            get {
                return ResourceManager.GetString("Hainan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 海南 的本地化字符串。
        /// </summary>
        internal static string Hainan2 {
            get {
                return ResourceManager.GetString("Hainan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 哈密 的本地化字符串。
        /// </summary>
        internal static string Hami {
            get {
                return ResourceManager.GetString("Hami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 韓城 的本地化字符串。
        /// </summary>
        internal static string Hancheng {
            get {
                return ResourceManager.GetString("Hancheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邯鄲 的本地化字符串。
        /// </summary>
        internal static string Handan {
            get {
                return ResourceManager.GetString("Handan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杭州 的本地化字符串。
        /// </summary>
        internal static string Hangzhou {
            get {
                return ResourceManager.GetString("Hangzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 漢中 的本地化字符串。
        /// </summary>
        internal static string Hanzhong {
            get {
                return ResourceManager.GetString("Hanzhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 哈爾濱 的本地化字符串。
        /// </summary>
        internal static string Harbin {
            get {
                return ResourceManager.GetString("Harbin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 河北 的本地化字符串。
        /// </summary>
        internal static string Hebei {
            get {
                return ResourceManager.GetString("Hebei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鶴壁 的本地化字符串。
        /// </summary>
        internal static string Hebi {
            get {
                return ResourceManager.GetString("Hebi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 河池 的本地化字符串。
        /// </summary>
        internal static string Hechi {
            get {
                return ResourceManager.GetString("Hechi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合肥 的本地化字符串。
        /// </summary>
        internal static string Hefei {
            get {
                return ResourceManager.GetString("Hefei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黑河 的本地化字符串。
        /// </summary>
        internal static string Heihe {
            get {
                return ResourceManager.GetString("Heihe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黑龍江 的本地化字符串。
        /// </summary>
        internal static string Heilongjiang {
            get {
                return ResourceManager.GetString("Heilongjiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 河南 的本地化字符串。
        /// </summary>
        internal static string Henan {
            get {
                return ResourceManager.GetString("Henan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 衡水 的本地化字符串。
        /// </summary>
        internal static string Hengshui {
            get {
                return ResourceManager.GetString("Hengshui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 衡陽 的本地化字符串。
        /// </summary>
        internal static string Hengyang {
            get {
                return ResourceManager.GetString("Hengyang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 海西 的本地化字符串。
        /// </summary>
        internal static string Hercynian {
            get {
                return ResourceManager.GetString("Hercynian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 河源 的本地化字符串。
        /// </summary>
        internal static string Heyuan {
            get {
                return ResourceManager.GetString("Heyuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菏澤 的本地化字符串。
        /// </summary>
        internal static string Heze {
            get {
                return ResourceManager.GetString("Heze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 賀州 的本地化字符串。
        /// </summary>
        internal static string Hezhou {
            get {
                return ResourceManager.GetString("Hezhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 呼和浩特 的本地化字符串。
        /// </summary>
        internal static string Hohhot {
            get {
                return ResourceManager.GetString("Hohhot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 香港 的本地化字符串。
        /// </summary>
        internal static string HongKong {
            get {
                return ResourceManager.GetString("HongKong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 和田 的本地化字符串。
        /// </summary>
        internal static string Hotan {
            get {
                return ResourceManager.GetString("Hotan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 淮安 的本地化字符串。
        /// </summary>
        internal static string Huaian {
            get {
                return ResourceManager.GetString("Huaian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 淮北 的本地化字符串。
        /// </summary>
        internal static string Huaibei {
            get {
                return ResourceManager.GetString("Huaibei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 懷化 的本地化字符串。
        /// </summary>
        internal static string Huaihua {
            get {
                return ResourceManager.GetString("Huaihua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 淮南 的本地化字符串。
        /// </summary>
        internal static string Huainan {
            get {
                return ResourceManager.GetString("Huainan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黃岡 的本地化字符串。
        /// </summary>
        internal static string Huanggang {
            get {
                return ResourceManager.GetString("Huanggang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黃南 的本地化字符串。
        /// </summary>
        internal static string HuangNan {
            get {
                return ResourceManager.GetString("HuangNan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黃山 的本地化字符串。
        /// </summary>
        internal static string Huangshan {
            get {
                return ResourceManager.GetString("Huangshan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 湖北 的本地化字符串。
        /// </summary>
        internal static string Hubei {
            get {
                return ResourceManager.GetString("Hubei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 惠州 的本地化字符串。
        /// </summary>
        internal static string Huizhou {
            get {
                return ResourceManager.GetString("Huizhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 葫蘆島 的本地化字符串。
        /// </summary>
        internal static string Huludao {
            get {
                return ResourceManager.GetString("Huludao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 呼倫貝爾 的本地化字符串。
        /// </summary>
        internal static string Hulunbeier {
            get {
                return ResourceManager.GetString("Hulunbeier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 湖南 的本地化字符串。
        /// </summary>
        internal static string Hunan {
            get {
                return ResourceManager.GetString("Hunan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 湖州 的本地化字符串。
        /// </summary>
        internal static string Huzhou {
            get {
                return ResourceManager.GetString("Huzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 內蒙古 的本地化字符串。
        /// </summary>
        internal static string InnerMongolia {
            get {
                return ResourceManager.GetString("InnerMongolia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 佳木斯 的本地化字符串。
        /// </summary>
        internal static string Jiamusi {
            get {
                return ResourceManager.GetString("Jiamusi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 江门 的本地化字符串。
        /// </summary>
        internal static string Jiangmen {
            get {
                return ResourceManager.GetString("Jiangmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 江蘇 的本地化字符串。
        /// </summary>
        internal static string Jiangsu {
            get {
                return ResourceManager.GetString("Jiangsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 江西 的本地化字符串。
        /// </summary>
        internal static string Jiangxi {
            get {
                return ResourceManager.GetString("Jiangxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 焦作 的本地化字符串。
        /// </summary>
        internal static string Jiaozuo {
            get {
                return ResourceManager.GetString("Jiaozuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 嘉興 的本地化字符串。
        /// </summary>
        internal static string Jiaxing {
            get {
                return ResourceManager.GetString("Jiaxing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 揭陽 的本地化字符串。
        /// </summary>
        internal static string Jieyang {
            get {
                return ResourceManager.GetString("Jieyang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吉林 的本地化字符串。
        /// </summary>
        internal static string Jilin {
            get {
                return ResourceManager.GetString("Jilin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 濟南 的本地化字符串。
        /// </summary>
        internal static string Jinan {
            get {
                return ResourceManager.GetString("Jinan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金昌 的本地化字符串。
        /// </summary>
        internal static string Jinchang {
            get {
                return ResourceManager.GetString("Jinchang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 晉城 的本地化字符串。
        /// </summary>
        internal static string Jincheng {
            get {
                return ResourceManager.GetString("Jincheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 景德鎮 的本地化字符串。
        /// </summary>
        internal static string Jingdezhen {
            get {
                return ResourceManager.GetString("Jingdezhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 荊门 的本地化字符串。
        /// </summary>
        internal static string Jingmen {
            get {
                return ResourceManager.GetString("Jingmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 荊州 的本地化字符串。
        /// </summary>
        internal static string Jingzhou {
            get {
                return ResourceManager.GetString("Jingzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金華 的本地化字符串。
        /// </summary>
        internal static string Jinhua {
            get {
                return ResourceManager.GetString("Jinhua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 濟寧 的本地化字符串。
        /// </summary>
        internal static string Jining {
            get {
                return ResourceManager.GetString("Jining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 晉中 的本地化字符串。
        /// </summary>
        internal static string Jinzhong {
            get {
                return ResourceManager.GetString("Jinzhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 錦州 的本地化字符串。
        /// </summary>
        internal static string Jinzhou {
            get {
                return ResourceManager.GetString("Jinzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吉首 的本地化字符串。
        /// </summary>
        internal static string Jishou {
            get {
                return ResourceManager.GetString("Jishou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 九江 的本地化字符串。
        /// </summary>
        internal static string Jiujiang {
            get {
                return ResourceManager.GetString("Jiujiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 酒泉 的本地化字符串。
        /// </summary>
        internal static string Jiuquan {
            get {
                return ResourceManager.GetString("Jiuquan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雞西 的本地化字符串。
        /// </summary>
        internal static string Jixi {
            get {
                return ResourceManager.GetString("Jixi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 開封 的本地化字符串。
        /// </summary>
        internal static string Kaifeng {
            get {
                return ResourceManager.GetString("Kaifeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高雄 的本地化字符串。
        /// </summary>
        internal static string Kaohsiung {
            get {
                return ResourceManager.GetString("Kaohsiung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 克拉瑪依 的本地化字符串。
        /// </summary>
        internal static string Karamay {
            get {
                return ResourceManager.GetString("Karamay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 喀什 的本地化字符串。
        /// </summary>
        internal static string Kashgar {
            get {
                return ResourceManager.GetString("Kashgar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库爾勒 的本地化字符串。
        /// </summary>
        internal static string Korla {
            get {
                return ResourceManager.GetString("Korla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昆明 的本地化字符串。
        /// </summary>
        internal static string Kunming {
            get {
                return ResourceManager.GetString("Kunming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昆山 的本地化字符串。
        /// </summary>
        internal static string Kunshan {
            get {
                return ResourceManager.GetString("Kunshan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 萊蕪 的本地化字符串。
        /// </summary>
        internal static string Laiwu {
            get {
                return ResourceManager.GetString("Laiwu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 廊坊 的本地化字符串。
        /// </summary>
        internal static string Langfang {
            get {
                return ResourceManager.GetString("Langfang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蘭州 的本地化字符串。
        /// </summary>
        internal static string Lanzhou {
            get {
                return ResourceManager.GetString("Lanzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 樂山 的本地化字符串。
        /// </summary>
        internal static string Leshan {
            get {
                return ResourceManager.GetString("Leshan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拉薩 的本地化字符串。
        /// </summary>
        internal static string Lhasa {
            get {
                return ResourceManager.GetString("Lhasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 涼山 的本地化字符串。
        /// </summary>
        internal static string Liangshan {
            get {
                return ResourceManager.GetString("Liangshan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连云港 的本地化字符串。
        /// </summary>
        internal static string Lianyungang {
            get {
                return ResourceManager.GetString("Lianyungang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 聊城 的本地化字符串。
        /// </summary>
        internal static string Liaocheng {
            get {
                return ResourceManager.GetString("Liaocheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遼寧 的本地化字符串。
        /// </summary>
        internal static string Liaoning {
            get {
                return ResourceManager.GetString("Liaoning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遼陽 的本地化字符串。
        /// </summary>
        internal static string Liaoyang {
            get {
                return ResourceManager.GetString("Liaoyang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遼源 的本地化字符串。
        /// </summary>
        internal static string Liaoyuan {
            get {
                return ResourceManager.GetString("Liaoyuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 麗江 的本地化字符串。
        /// </summary>
        internal static string Lijiang {
            get {
                return ResourceManager.GetString("Lijiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 临滄 的本地化字符串。
        /// </summary>
        internal static string Lincang {
            get {
                return ResourceManager.GetString("Lincang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 临汾 的本地化字符串。
        /// </summary>
        internal static string Linfen {
            get {
                return ResourceManager.GetString("Linfen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 临夏 的本地化字符串。
        /// </summary>
        internal static string Linxia {
            get {
                return ResourceManager.GetString("Linxia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 临沂 的本地化字符串。
        /// </summary>
        internal static string Linyi {
            get {
                return ResourceManager.GetString("Linyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 麗水 的本地化字符串。
        /// </summary>
        internal static string Lishui {
            get {
                return ResourceManager.GetString("Lishui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 六盤水 的本地化字符串。
        /// </summary>
        internal static string Liupanshui {
            get {
                return ResourceManager.GetString("Liupanshui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 柳州 的本地化字符串。
        /// </summary>
        internal static string Liuzhou {
            get {
                return ResourceManager.GetString("Liuzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 龍巖 的本地化字符串。
        /// </summary>
        internal static string Longyan {
            get {
                return ResourceManager.GetString("Longyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 婁底 的本地化字符串。
        /// </summary>
        internal static string Loudi {
            get {
                return ResourceManager.GetString("Loudi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 六安 的本地化字符串。
        /// </summary>
        internal static string Luan {
            get {
                return ResourceManager.GetString("Luan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 呂梁 的本地化字符串。
        /// </summary>
        internal static string Luliang {
            get {
                return ResourceManager.GetString("Luliang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 漯河 的本地化字符串。
        /// </summary>
        internal static string Luohe {
            get {
                return ResourceManager.GetString("Luohe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 洛陽 的本地化字符串。
        /// </summary>
        internal static string Luoyang {
            get {
                return ResourceManager.GetString("Luoyang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 瀘州 的本地化字符串。
        /// </summary>
        internal static string Luzhou {
            get {
                return ResourceManager.GetString("Luzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 澳门 的本地化字符串。
        /// </summary>
        internal static string Macao {
            get {
                return ResourceManager.GetString("Macao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 茂名 的本地化字符串。
        /// </summary>
        internal static string Maoming {
            get {
                return ResourceManager.GetString("Maoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 馬鞍山 的本地化字符串。
        /// </summary>
        internal static string MaOnShan {
            get {
                return ResourceManager.GetString("MaOnShan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 松原 的本地化字符串。
        /// </summary>
        internal static string Matsubara {
            get {
                return ResourceManager.GetString("Matsubara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 梅州 的本地化字符串。
        /// </summary>
        internal static string Meizhou {
            get {
                return ResourceManager.GetString("Meizhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 綿陽 的本地化字符串。
        /// </summary>
        internal static string Mianyang {
            get {
                return ResourceManager.GetString("Mianyang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 牡丹江 的本地化字符串。
        /// </summary>
        internal static string Mudanjiang {
            get {
                return ResourceManager.GetString("Mudanjiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直轄市 的本地化字符串。
        /// </summary>
        internal static string Municipality {
            get {
                return ResourceManager.GetString("Municipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 那曲 的本地化字符串。
        /// </summary>
        internal static string Nagqu {
            get {
                return ResourceManager.GetString("Nagqu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 南昌 的本地化字符串。
        /// </summary>
        internal static string Nanchang {
            get {
                return ResourceManager.GetString("Nanchang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 南京 的本地化字符串。
        /// </summary>
        internal static string Nanjing {
            get {
                return ResourceManager.GetString("Nanjing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 南寧 的本地化字符串。
        /// </summary>
        internal static string Nanning {
            get {
                return ResourceManager.GetString("Nanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 南平 的本地化字符串。
        /// </summary>
        internal static string Nanping {
            get {
                return ResourceManager.GetString("Nanping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 南通 的本地化字符串。
        /// </summary>
        internal static string Nantong {
            get {
                return ResourceManager.GetString("Nantong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 南陽 的本地化字符串。
        /// </summary>
        internal static string Nanyang {
            get {
                return ResourceManager.GetString("Nanyang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 內江 的本地化字符串。
        /// </summary>
        internal static string Neijiang {
            get {
                return ResourceManager.GetString("Neijiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寧波 的本地化字符串。
        /// </summary>
        internal static string Ningbo {
            get {
                return ResourceManager.GetString("Ningbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寧德 的本地化字符串。
        /// </summary>
        internal static string Ningde {
            get {
                return ResourceManager.GetString("Ningde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寧夏 的本地化字符串。
        /// </summary>
        internal static string Ningxia {
            get {
                return ResourceManager.GetString("Ningxia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 北海 的本地化字符串。
        /// </summary>
        internal static string NorthSea {
            get {
                return ResourceManager.GetString("NorthSea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 怒江 的本地化字符串。
        /// </summary>
        internal static string NuRiver {
            get {
                return ResourceManager.GetString("NuRiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 林芝 的本地化字符串。
        /// </summary>
        internal static string Nyingchi {
            get {
                return ResourceManager.GetString("Nyingchi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鄂爾多斯 的本地化字符串。
        /// </summary>
        internal static string Ordos {
            get {
                return ResourceManager.GetString("Ordos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 巴中 的本地化字符串。
        /// </summary>
        internal static string Pakistan {
            get {
                return ResourceManager.GetString("Pakistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盤錦 的本地化字符串。
        /// </summary>
        internal static string Panjin {
            get {
                return ResourceManager.GetString("Panjin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 攀枝花 的本地化字符串。
        /// </summary>
        internal static string Panzhihua {
            get {
                return ResourceManager.GetString("Panzhihua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平頂山 的本地化字符串。
        /// </summary>
        internal static string Pingdingshan {
            get {
                return ResourceManager.GetString("Pingdingshan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平涼 的本地化字符串。
        /// </summary>
        internal static string Pingliang {
            get {
                return ResourceManager.GetString("Pingliang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 萍鄉 的本地化字符串。
        /// </summary>
        internal static string Pingxiang {
            get {
                return ResourceManager.GetString("Pingxiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 莆田 的本地化字符串。
        /// </summary>
        internal static string Putian {
            get {
                return ResourceManager.GetString("Putian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 濮陽 的本地化字符串。
        /// </summary>
        internal static string Puyang {
            get {
                return ResourceManager.GetString("Puyang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昌都 的本地化字符串。
        /// </summary>
        internal static string Qamdo {
            get {
                return ResourceManager.GetString("Qamdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 青島 的本地化字符串。
        /// </summary>
        internal static string Qingdao {
            get {
                return ResourceManager.GetString("Qingdao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 青海 的本地化字符串。
        /// </summary>
        internal static string Qinghai {
            get {
                return ResourceManager.GetString("Qinghai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 慶陽 的本地化字符串。
        /// </summary>
        internal static string Qingyang {
            get {
                return ResourceManager.GetString("Qingyang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清遠 的本地化字符串。
        /// </summary>
        internal static string Qingyuan {
            get {
                return ResourceManager.GetString("Qingyuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秦皇島 的本地化字符串。
        /// </summary>
        internal static string Qinhuangdao {
            get {
                return ResourceManager.GetString("Qinhuangdao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欽州 的本地化字符串。
        /// </summary>
        internal static string Qinzhou {
            get {
                return ResourceManager.GetString("Qinzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 瓊山 的本地化字符串。
        /// </summary>
        internal static string Qiongshan {
            get {
                return ResourceManager.GetString("Qiongshan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 齊齊哈爾 的本地化字符串。
        /// </summary>
        internal static string Qiqihar {
            get {
                return ResourceManager.GetString("Qiqihar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 七台河 的本地化字符串。
        /// </summary>
        internal static string Qitaihe {
            get {
                return ResourceManager.GetString("Qitaihe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泉州 的本地化字符串。
        /// </summary>
        internal static string Quanzhou {
            get {
                return ResourceManager.GetString("Quanzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲阜 的本地化字符串。
        /// </summary>
        internal static string Qufu {
            get {
                return ResourceManager.GetString("Qufu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲靖 的本地化字符串。
        /// </summary>
        internal static string Qujing {
            get {
                return ResourceManager.GetString("Qujing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 衢州 的本地化字符串。
        /// </summary>
        internal static string Quzhou {
            get {
                return ResourceManager.GetString("Quzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紅河 的本地化字符串。
        /// </summary>
        internal static string RedRiver {
            get {
                return ResourceManager.GetString("RedRiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三门峽 的本地化字符串。
        /// </summary>
        internal static string Sanmenxia {
            get {
                return ResourceManager.GetString("Sanmenxia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三明 的本地化字符串。
        /// </summary>
        internal static string Sanming {
            get {
                return ResourceManager.GetString("Sanming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三亞 的本地化字符串。
        /// </summary>
        internal static string Sanya {
            get {
                return ResourceManager.GetString("Sanya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 陝西 的本地化字符串。
        /// </summary>
        internal static string Shaanxi {
            get {
                return ResourceManager.GetString("Shaanxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 山東 的本地化字符串。
        /// </summary>
        internal static string Shandong {
            get {
                return ResourceManager.GetString("Shandong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上海 的本地化字符串。
        /// </summary>
        internal static string Shanghai {
            get {
                return ResourceManager.GetString("Shanghai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商洛 的本地化字符串。
        /// </summary>
        internal static string Shangluo {
            get {
                return ResourceManager.GetString("Shangluo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商丘 的本地化字符串。
        /// </summary>
        internal static string Shangqiu {
            get {
                return ResourceManager.GetString("Shangqiu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上饒 的本地化字符串。
        /// </summary>
        internal static string Shangrao {
            get {
                return ResourceManager.GetString("Shangrao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 山南 的本地化字符串。
        /// </summary>
        internal static string Shannan {
            get {
                return ResourceManager.GetString("Shannan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 汕尾 的本地化字符串。
        /// </summary>
        internal static string Shanwei {
            get {
                return ResourceManager.GetString("Shanwei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 山西 的本地化字符串。
        /// </summary>
        internal static string Shanxi {
            get {
                return ResourceManager.GetString("Shanxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 韶开 的本地化字符串。
        /// </summary>
        internal static string Shaoguan {
            get {
                return ResourceManager.GetString("Shaoguan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 韶山 的本地化字符串。
        /// </summary>
        internal static string Shaoshan {
            get {
                return ResourceManager.GetString("Shaoshan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紹興 的本地化字符串。
        /// </summary>
        internal static string Shaoxing {
            get {
                return ResourceManager.GetString("Shaoxing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邵陽 的本地化字符串。
        /// </summary>
        internal static string Shaoyang {
            get {
                return ResourceManager.GetString("Shaoyang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 神農架 的本地化字符串。
        /// </summary>
        internal static string Shennongjia {
            get {
                return ResourceManager.GetString("Shennongjia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 瀋陽 的本地化字符串。
        /// </summary>
        internal static string Shenyang {
            get {
                return ResourceManager.GetString("Shenyang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深圳 的本地化字符串。
        /// </summary>
        internal static string Shenzhen {
            get {
                return ResourceManager.GetString("Shenzhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日喀則 的本地化字符串。
        /// </summary>
        internal static string Shigatse {
            get {
                return ResourceManager.GetString("Shigatse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 石河子 的本地化字符串。
        /// </summary>
        internal static string Shihezi {
            get {
                return ResourceManager.GetString("Shihezi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 石家莊 的本地化字符串。
        /// </summary>
        internal static string Shijiazhuang {
            get {
                return ResourceManager.GetString("Shijiazhuang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 十堰 的本地化字符串。
        /// </summary>
        internal static string Shiyan {
            get {
                return ResourceManager.GetString("Shiyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 石嘴山 的本地化字符串。
        /// </summary>
        internal static string Shizuishan {
            get {
                return ResourceManager.GetString("Shizuishan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雙鴨山 的本地化字符串。
        /// </summary>
        internal static string Shuangyashan {
            get {
                return ResourceManager.GetString("Shuangyashan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 朔州 的本地化字符串。
        /// </summary>
        internal static string Shuozhou {
            get {
                return ResourceManager.GetString("Shuozhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 四川 的本地化字符串。
        /// </summary>
        internal static string Sichuan {
            get {
                return ResourceManager.GetString("Sichuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 白銀 的本地化字符串。
        /// </summary>
        internal static string silver {
            get {
                return ResourceManager.GetString("silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 思茅 的本地化字符串。
        /// </summary>
        internal static string Simao {
            get {
                return ResourceManager.GetString("Simao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 四平 的本地化字符串。
        /// </summary>
        internal static string Siping {
            get {
                return ResourceManager.GetString("Siping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特別行政区 的本地化字符串。
        /// </summary>
        internal static string SpecialArea {
            get {
                return ResourceManager.GetString("SpecialArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 綏化 的本地化字符串。
        /// </summary>
        internal static string Suihua {
            get {
                return ResourceManager.GetString("Suihua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遂寧 的本地化字符串。
        /// </summary>
        internal static string Suining {
            get {
                return ResourceManager.GetString("Suining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隨州 的本地化字符串。
        /// </summary>
        internal static string Suizhou {
            get {
                return ResourceManager.GetString("Suizhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日照 的本地化字符串。
        /// </summary>
        internal static string sunshine {
            get {
                return ResourceManager.GetString("sunshine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宿遷 的本地化字符串。
        /// </summary>
        internal static string Suqian {
            get {
                return ResourceManager.GetString("Suqian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蘇州 的本地化字符串。
        /// </summary>
        internal static string Suzhou {
            get {
                return ResourceManager.GetString("Suzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宿州 的本地化字符串。
        /// </summary>
        internal static string Suzhou2 {
            get {
                return ResourceManager.GetString("Suzhou2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 塔城 的本地化字符串。
        /// </summary>
        internal static string Tacheng {
            get {
                return ResourceManager.GetString("Tacheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泰安 的本地化字符串。
        /// </summary>
        internal static string Taian {
            get {
                return ResourceManager.GetString("Taian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 太倉 的本地化字符串。
        /// </summary>
        internal static string Taicang {
            get {
                return ResourceManager.GetString("Taicang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 台北 的本地化字符串。
        /// </summary>
        internal static string Taipei {
            get {
                return ResourceManager.GetString("Taipei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 台灣 的本地化字符串。
        /// </summary>
        internal static string Taiwan {
            get {
                return ResourceManager.GetString("Taiwan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 太原 的本地化字符串。
        /// </summary>
        internal static string Taiyuan {
            get {
                return ResourceManager.GetString("Taiyuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泰州 的本地化字符串。
        /// </summary>
        internal static string Taizhou {
            get {
                return ResourceManager.GetString("Taizhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 台州 的本地化字符串。
        /// </summary>
        internal static string Taizhou2 {
            get {
                return ResourceManager.GetString("Taizhou2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 唐山 的本地化字符串。
        /// </summary>
        internal static string Tangshan {
            get {
                return ResourceManager.GetString("Tangshan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 德州 的本地化字符串。
        /// </summary>
        internal static string Texas {
            get {
                return ResourceManager.GetString("Texas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通什 的本地化字符串。
        /// </summary>
        internal static string Through {
            get {
                return ResourceManager.GetString("Through", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天津 的本地化字符串。
        /// </summary>
        internal static string Tianjin {
            get {
                return ResourceManager.GetString("Tianjin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天水 的本地化字符串。
        /// </summary>
        internal static string Tianshui {
            get {
                return ResourceManager.GetString("Tianshui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 西藏 的本地化字符串。
        /// </summary>
        internal static string Tibet {
            get {
                return ResourceManager.GetString("Tibet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鐵嶺 的本地化字符串。
        /// </summary>
        internal static string Tieling {
            get {
                return ResourceManager.GetString("Tieling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 銅川 的本地化字符串。
        /// </summary>
        internal static string Tongchuan {
            get {
                return ResourceManager.GetString("Tongchuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通化 的本地化字符串。
        /// </summary>
        internal static string Tonghua {
            get {
                return ResourceManager.GetString("Tonghua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通遼 的本地化字符串。
        /// </summary>
        internal static string Tongliao {
            get {
                return ResourceManager.GetString("Tongliao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 銅陵 的本地化字符串。
        /// </summary>
        internal static string Tongling {
            get {
                return ResourceManager.GetString("Tongling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 銅仁 的本地化字符串。
        /// </summary>
        internal static string Tongren {
            get {
                return ResourceManager.GetString("Tongren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鶴岡 的本地化字符串。
        /// </summary>
        internal static string Tsuruoka {
            get {
                return ResourceManager.GetString("Tsuruoka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吐魯番 的本地化字符串。
        /// </summary>
        internal static string Turpan {
            get {
                return ResourceManager.GetString("Turpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 烏魯木齊 的本地化字符串。
        /// </summary>
        internal static string Urumqi {
            get {
                return ResourceManager.GetString("Urumqi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 濰坊 的本地化字符串。
        /// </summary>
        internal static string Weifang {
            get {
                return ResourceManager.GetString("Weifang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 威海 的本地化字符串。
        /// </summary>
        internal static string Weihai {
            get {
                return ResourceManager.GetString("Weihai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渭南 的本地化字符串。
        /// </summary>
        internal static string Weinan {
            get {
                return ResourceManager.GetString("Weinan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文昌 的本地化字符串。
        /// </summary>
        internal static string Wenchang {
            get {
                return ResourceManager.GetString("Wenchang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文山 的本地化字符串。
        /// </summary>
        internal static string Wenshan {
            get {
                return ResourceManager.GetString("Wenshan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 溫州 的本地化字符串。
        /// </summary>
        internal static string Wenzhou {
            get {
                return ResourceManager.GetString("Wenzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 白城 的本地化字符串。
        /// </summary>
        internal static string WhiteCity {
            get {
                return ResourceManager.GetString("WhiteCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 白山 的本地化字符串。
        /// </summary>
        internal static string WhiteMountain {
            get {
                return ResourceManager.GetString("WhiteMountain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吳縣 的本地化字符串。
        /// </summary>
        internal static string WuCounty {
            get {
                return ResourceManager.GetString("WuCounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 烏海 的本地化字符串。
        /// </summary>
        internal static string Wuhai {
            get {
                return ResourceManager.GetString("Wuhai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 武漢 的本地化字符串。
        /// </summary>
        internal static string Wuhan {
            get {
                return ResourceManager.GetString("Wuhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蕪湖 的本地化字符串。
        /// </summary>
        internal static string Wuhu {
            get {
                return ResourceManager.GetString("Wuhu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 武威 的本地化字符串。
        /// </summary>
        internal static string Wuwei {
            get {
                return ResourceManager.GetString("Wuwei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无錫 的本地化字符串。
        /// </summary>
        internal static string Wuxi {
            get {
                return ResourceManager.GetString("Wuxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吳忠 的本地化字符串。
        /// </summary>
        internal static string WuZhong {
            get {
                return ResourceManager.GetString("WuZhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 梧州 的本地化字符串。
        /// </summary>
        internal static string Wuzhou {
            get {
                return ResourceManager.GetString("Wuzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 廈门 的本地化字符串。
        /// </summary>
        internal static string Xiamen {
            get {
                return ResourceManager.GetString("Xiamen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 西安 的本地化字符串。
        /// </summary>
        internal static string Xian {
            get {
                return ResourceManager.GetString("Xian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 湘潭 的本地化字符串。
        /// </summary>
        internal static string Xiangtan {
            get {
                return ResourceManager.GetString("Xiangtan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 襄陽 的本地化字符串。
        /// </summary>
        internal static string Xiangyang {
            get {
                return ResourceManager.GetString("Xiangyang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 咸寧 的本地化字符串。
        /// </summary>
        internal static string Xianning {
            get {
                return ResourceManager.GetString("Xianning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 咸陽 的本地化字符串。
        /// </summary>
        internal static string Xianyang {
            get {
                return ResourceManager.GetString("Xianyang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 孝感 的本地化字符串。
        /// </summary>
        internal static string Xiaogan {
            get {
                return ResourceManager.GetString("Xiaogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 錫林浩特 的本地化字符串。
        /// </summary>
        internal static string Xilinhot {
            get {
                return ResourceManager.GetString("Xilinhot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邢台 的本地化字符串。
        /// </summary>
        internal static string Xingtai {
            get {
                return ResourceManager.GetString("Xingtai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 西寧 的本地化字符串。
        /// </summary>
        internal static string Xining {
            get {
                return ResourceManager.GetString("Xining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新疆 的本地化字符串。
        /// </summary>
        internal static string Xinjiang {
            get {
                return ResourceManager.GetString("Xinjiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新鄉 的本地化字符串。
        /// </summary>
        internal static string Xinxiang {
            get {
                return ResourceManager.GetString("Xinxiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信陽 的本地化字符串。
        /// </summary>
        internal static string Xinyang {
            get {
                return ResourceManager.GetString("Xinyang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新余 的本地化字符串。
        /// </summary>
        internal static string Xinyu {
            get {
                return ResourceManager.GetString("Xinyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忻州 的本地化字符串。
        /// </summary>
        internal static string Xinzhou {
            get {
                return ResourceManager.GetString("Xinzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宣城 的本地化字符串。
        /// </summary>
        internal static string Xuancheng {
            get {
                return ResourceManager.GetString("Xuancheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 許昌 的本地化字符串。
        /// </summary>
        internal static string Xuchang {
            get {
                return ResourceManager.GetString("Xuchang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 徐州 的本地化字符串。
        /// </summary>
        internal static string Xuzhou {
            get {
                return ResourceManager.GetString("Xuzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雅安 的本地化字符串。
        /// </summary>
        internal static string Yaan {
            get {
                return ResourceManager.GetString("Yaan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 延安 的本地化字符串。
        /// </summary>
        internal static string Yanan {
            get {
                return ResourceManager.GetString("Yanan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 延邊 的本地化字符串。
        /// </summary>
        internal static string Yanbian {
            get {
                return ResourceManager.GetString("Yanbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鹽城 的本地化字符串。
        /// </summary>
        internal static string Yancheng {
            get {
                return ResourceManager.GetString("Yancheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雁盪山 的本地化字符串。
        /// </summary>
        internal static string YandangMountain {
            get {
                return ResourceManager.GetString("YandangMountain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 陽江 的本地化字符串。
        /// </summary>
        internal static string Yangjiang {
            get {
                return ResourceManager.GetString("Yangjiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 陽泉 的本地化字符串。
        /// </summary>
        internal static string Yangquan {
            get {
                return ResourceManager.GetString("Yangquan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 陽朔 的本地化字符串。
        /// </summary>
        internal static string Yangshuo {
            get {
                return ResourceManager.GetString("Yangshuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 揚州 的本地化字符串。
        /// </summary>
        internal static string Yangzhou {
            get {
                return ResourceManager.GetString("Yangzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 煙臺 的本地化字符串。
        /// </summary>
        internal static string Yantai {
            get {
                return ResourceManager.GetString("Yantai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黃石 的本地化字符串。
        /// </summary>
        internal static string Yellowstone {
            get {
                return ResourceManager.GetString("Yellowstone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宜賓 的本地化字符串。
        /// </summary>
        internal static string Yibin {
            get {
                return ResourceManager.GetString("Yibin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宜昌 的本地化字符串。
        /// </summary>
        internal static string Yichang {
            get {
                return ResourceManager.GetString("Yichang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伊春 的本地化字符串。
        /// </summary>
        internal static string Yichun {
            get {
                return ResourceManager.GetString("Yichun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宜春 的本地化字符串。
        /// </summary>
        internal static string Yichun2 {
            get {
                return ResourceManager.GetString("Yichun2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 銀川 的本地化字符串。
        /// </summary>
        internal static string Yinchuan {
            get {
                return ResourceManager.GetString("Yinchuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 營口 的本地化字符串。
        /// </summary>
        internal static string Yingkou {
            get {
                return ResourceManager.GetString("Yingkou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鷹潭 的本地化字符串。
        /// </summary>
        internal static string Yingtan {
            get {
                return ResourceManager.GetString("Yingtan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伊寧 的本地化字符串。
        /// </summary>
        internal static string Yining {
            get {
                return ResourceManager.GetString("Yining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宜興 的本地化字符串。
        /// </summary>
        internal static string Yixing {
            get {
                return ResourceManager.GetString("Yixing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 益陽 的本地化字符串。
        /// </summary>
        internal static string Yiyang {
            get {
                return ResourceManager.GetString("Yiyang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 永州 的本地化字符串。
        /// </summary>
        internal static string Yongzhou {
            get {
                return ResourceManager.GetString("Yongzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 岳陽 的本地化字符串。
        /// </summary>
        internal static string Yueyang {
            get {
                return ResourceManager.GetString("Yueyang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 榆林 的本地化字符串。
        /// </summary>
        internal static string Yulin {
            get {
                return ResourceManager.GetString("Yulin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玉林 的本地化字符串。
        /// </summary>
        internal static string Yulin2 {
            get {
                return ResourceManager.GetString("Yulin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 運城 的本地化字符串。
        /// </summary>
        internal static string Yuncheng {
            get {
                return ResourceManager.GetString("Yuncheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 云浮 的本地化字符串。
        /// </summary>
        internal static string Yunfu {
            get {
                return ResourceManager.GetString("Yunfu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 云南 的本地化字符串。
        /// </summary>
        internal static string Yunnan {
            get {
                return ResourceManager.GetString("Yunnan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玉樹 的本地化字符串。
        /// </summary>
        internal static string Yushu {
            get {
                return ResourceManager.GetString("Yushu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玉溪 的本地化字符串。
        /// </summary>
        internal static string Yuxi {
            get {
                return ResourceManager.GetString("Yuxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 棗莊 的本地化字符串。
        /// </summary>
        internal static string Zaozhuang {
            get {
                return ResourceManager.GetString("Zaozhuang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 張家界 的本地化字符串。
        /// </summary>
        internal static string Zhangjiajie {
            get {
                return ResourceManager.GetString("Zhangjiajie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 張家口 的本地化字符串。
        /// </summary>
        internal static string Zhangjiakou {
            get {
                return ResourceManager.GetString("Zhangjiakou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 張掖 的本地化字符串。
        /// </summary>
        internal static string Zhangye {
            get {
                return ResourceManager.GetString("Zhangye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 漳州 的本地化字符串。
        /// </summary>
        internal static string Zhangzhou {
            get {
                return ResourceManager.GetString("Zhangzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 湛江 的本地化字符串。
        /// </summary>
        internal static string Zhanjiang {
            get {
                return ResourceManager.GetString("Zhanjiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 肇慶 的本地化字符串。
        /// </summary>
        internal static string Zhaoqing {
            get {
                return ResourceManager.GetString("Zhaoqing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昭通 的本地化字符串。
        /// </summary>
        internal static string Zhaotong {
            get {
                return ResourceManager.GetString("Zhaotong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浙江 的本地化字符串。
        /// </summary>
        internal static string Zhejiang {
            get {
                return ResourceManager.GetString("Zhejiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鄭州 的本地化字符串。
        /// </summary>
        internal static string Zhengzhou {
            get {
                return ResourceManager.GetString("Zhengzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鎮江 的本地化字符串。
        /// </summary>
        internal static string Zhenjiang {
            get {
                return ResourceManager.GetString("Zhenjiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中山 的本地化字符串。
        /// </summary>
        internal static string Zhongshan {
            get {
                return ResourceManager.GetString("Zhongshan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周口 的本地化字符串。
        /// </summary>
        internal static string Zhoukou {
            get {
                return ResourceManager.GetString("Zhoukou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 舟山 的本地化字符串。
        /// </summary>
        internal static string Zhoushan {
            get {
                return ResourceManager.GetString("Zhoushan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 駐馬店 的本地化字符串。
        /// </summary>
        internal static string Zhumadian {
            get {
                return ResourceManager.GetString("Zhumadian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 株洲 的本地化字符串。
        /// </summary>
        internal static string Zhuzhou {
            get {
                return ResourceManager.GetString("Zhuzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 淄博 的本地化字符串。
        /// </summary>
        internal static string Zibo {
            get {
                return ResourceManager.GetString("Zibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自貢 的本地化字符串。
        /// </summary>
        internal static string Zigong {
            get {
                return ResourceManager.GetString("Zigong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 資陽 的本地化字符串。
        /// </summary>
        internal static string Ziyang {
            get {
                return ResourceManager.GetString("Ziyang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遵義 的本地化字符串。
        /// </summary>
        internal static string Zunyi {
            get {
                return ResourceManager.GetString("Zunyi", resourceCulture);
            }
        }
    }
}
