//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMServer {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICMServer.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 地址簿升级 的本地化字符串。
        /// </summary>
        internal static string AddrBookUpgrade {
            get {
                return ResourceManager.GetString("AddrBookUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理机 的本地化字符串。
        /// </summary>
        internal static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广告标题 的本地化字符串。
        /// </summary>
        internal static string AdsTitle {
            get {
                return ResourceManager.GetString("AdsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广告标题和文件位置不得为空 的本地化字符串。
        /// </summary>
        internal static string AdsTitleAndFilePathCannotBeNull {
            get {
                return ResourceManager.GetString("AdsTitleAndFilePathCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布时间 的本地化字符串。
        /// </summary>
        internal static string AnnounceTime {
            get {
                return ResourceManager.GetString("AnnounceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小区门口机 的本地化字符串。
        /// </summary>
        internal static string areadoorbell {
            get {
                return ResourceManager.GetString("areadoorbell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定要刪除全部资料？ 的本地化字符串。
        /// </summary>
        internal static string AreYouSureDelAll {
            get {
                return ResourceManager.GetString("AreYouSureDelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定要刪除此笔资料？ 的本地化字符串。
        /// </summary>
        internal static string AreYouSureDelThis {
            get {
                return ResourceManager.GetString("AreYouSureDelThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不得为空 的本地化字符串。
        /// </summary>
        internal static string CantBeNull {
            get {
                return ResourceManager.GetString("CantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡号长度10位 的本地化字符串。
        /// </summary>
        internal static string CardCannotLessThan10 {
            get {
                return ResourceManager.GetString("CardCannotLessThan10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡号已存在，无法保存！ 的本地化字符串。
        /// </summary>
        internal static string CardExistCannotSave {
            get {
                return ResourceManager.GetString("CardExistCannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效期 的本地化字符串。
        /// </summary>
        internal static string CardExpireDate {
            get {
                return ResourceManager.GetString("CardExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效状态 的本地化字符串。
        /// </summary>
        internal static string CardExpireStatus {
            get {
                return ResourceManager.GetString("CardExpireStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡号 的本地化字符串。
        /// </summary>
        internal static string CardID {
            get {
                return ResourceManager.GetString("CardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡号、房号、姓名不得为空! 的本地化字符串。
        /// </summary>
        internal static string CardRoNameCannotBeNull {
            get {
                return ResourceManager.GetString("CardRoNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡类型 的本地化字符串。
        /// </summary>
        internal static string CardType {
            get {
                return ResourceManager.GetString("CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 门禁卡升级 的本地化字符串。
        /// </summary>
        internal static string CardUpgarde {
            get {
                return ResourceManager.GetString("CardUpgarde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 层 的本地化字符串。
        /// </summary>
        internal static string ceng {
            get {
                return ResourceManager.GetString("ceng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库备份完成 的本地化字符串。
        /// </summary>
        internal static string DBBackupFinish {
            get {
                return ResourceManager.GetString("DBBackupFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库还原完成 的本地化字符串。
        /// </summary>
        internal static string DBRecoverFinish {
            get {
                return ResourceManager.GetString("DBRecoverFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 栋 的本地化字符串。
        /// </summary>
        internal static string dong {
            get {
                return ResourceManager.GetString("dong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 楼栋门口机 的本地化字符串。
        /// </summary>
        internal static string dongdoorbell {
            get {
                return ResourceManager.GetString("dongdoorbell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分机 的本地化字符串。
        /// </summary>
        internal static string ext {
            get {
                return ResourceManager.GetString("ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 档案名和档案位置不得为空 的本地化字符串。
        /// </summary>
        internal static string FileNameAndPathCannotBeNull {
            get {
                return ResourceManager.GetString("FileNameAndPathCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件不存在 的本地化字符串。
        /// </summary>
        internal static string FilePathNotExist {
            get {
                return ResourceManager.GetString("FilePathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件保存地址 的本地化字符串。
        /// </summary>
        internal static string FileSavePath {
            get {
                return ResourceManager.GetString("FileSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件升级 的本地化字符串。
        /// </summary>
        internal static string FirmwareUpgrade {
            get {
                return ResourceManager.GetString("FirmwareUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已处理 的本地化字符串。
        /// </summary>
        internal static string hasDeal {
            get {
                return ResourceManager.GetString("hasDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已处理 的本地化字符串。
        /// </summary>
        internal static string hashandle {
            get {
                return ResourceManager.GetString("hashandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已读 的本地化字符串。
        /// </summary>
        internal static string hasRead {
            get {
                return ResourceManager.GetString("hasRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 室内机 的本地化字符串。
        /// </summary>
        internal static string indoor {
            get {
                return ResourceManager.GetString("indoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 室内机 (SD) 的本地化字符串。
        /// </summary>
        internal static string indoorSD {
            get {
                return ResourceManager.GetString("indoorSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP摄像头 的本地化字符串。
        /// </summary>
        internal static string ipcam {
            get {
                return ResourceManager.GetString("ipcam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此IP不存在 的本地化字符串。
        /// </summary>
        internal static string IPNotExist {
            get {
                return ResourceManager.GetString("IPNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效 的本地化字符串。
        /// </summary>
        internal static string IsWorking {
            get {
                return ResourceManager.GetString("IsWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 门口机地址 的本地化字符串。
        /// </summary>
        internal static string leaveMsgDoorAddr {
            get {
                return ResourceManager.GetString("leaveMsgDoorAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 室內房号 的本地化字符串。
        /// </summary>
        internal static string leaveMsgIndoorRo {
            get {
                return ResourceManager.GetString("leaveMsgIndoorRo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        internal static string leaveMsgTme {
            get {
                return ResourceManager.GetString("leaveMsgTme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理人员 的本地化字符串。
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机 的本地化字符串。
        /// </summary>
        internal static string mobile {
            get {
                return ResourceManager.GetString("mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息格式 的本地化字符串。
        /// </summary>
        internal static string MsgFormat {
            get {
                return ResourceManager.GetString("MsgFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息类型 的本地化字符串。
        /// </summary>
        internal static string MsgType {
            get {
                return ResourceManager.GetString("MsgType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查无結果! 的本地化字符串。
        /// </summary>
        internal static string NoResult {
            get {
                return ResourceManager.GetString("NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未处理 的本地化字符串。
        /// </summary>
        internal static string notDeal {
            get {
                return ResourceManager.GetString("notDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未处理 的本地化字符串。
        /// </summary>
        internal static string nothandle {
            get {
                return ResourceManager.GetString("nothandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未读 的本地化字符串。
        /// </summary>
        internal static string notRead {
            get {
                return ResourceManager.GetString("notRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效 的本地化字符串。
        /// </summary>
        internal static string NotWorking {
            get {
                return ResourceManager.GetString("NotWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线 的本地化字符串。
        /// </summary>
        internal static string offline {
            get {
                return ResourceManager.GetString("offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线 的本地化字符串。
        /// </summary>
        internal static string online {
            get {
                return ResourceManager.GetString("online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启旧档 的本地化字符串。
        /// </summary>
        internal static string OpenOldFile {
            get {
                return ResourceManager.GetString("OpenOldFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作人员編号 的本地化字符串。
        /// </summary>
        internal static string OperatorID {
            get {
                return ResourceManager.GetString("OperatorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作人员姓名 的本地化字符串。
        /// </summary>
        internal static string OperatorName {
            get {
                return ResourceManager.GetString("OperatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作人员权限组 的本地化字符串。
        /// </summary>
        internal static string OperatorPermissionGroup {
            get {
                return ResourceManager.GetString("OperatorPermissionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他类型 的本地化字符串。
        /// </summary>
        internal static string OtherType {
            get {
                return ResourceManager.GetString("OtherType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径 的本地化字符串。
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限组 的本地化字符串。
        /// </summary>
        internal static string PermissionGroup {
            get {
                return ResourceManager.GetString("PermissionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放时序 的本地化字符串。
        /// </summary>
        internal static string PlaySequence {
            get {
                return ResourceManager.GetString("PlaySequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入密码 的本地化字符串。
        /// </summary>
        internal static string plzEnterPw {
            get {
                return ResourceManager.GetString("plzEnterPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入查询条件! 的本地化字符串。
        /// </summary>
        internal static string plzEnterQueryCondition {
            get {
                return ResourceManager.GetString("plzEnterQueryCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择某一&apos;室&apos; 的本地化字符串。
        /// </summary>
        internal static string plzSelectARoom {
            get {
                return ResourceManager.GetString("plzSelectARoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公共门铃机 的本地化字符串。
        /// </summary>
        internal static string pubdoorbell {
            get {
                return ResourceManager.GetString("pubdoorbell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 兩次输入的密码不一致！ 的本地化字符串。
        /// </summary>
        internal static string PwEnterNotTheSame {
            get {
                return ResourceManager.GetString("PwEnterNotTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区 的本地化字符串。
        /// </summary>
        internal static string qu {
            get {
                return ResourceManager.GetString("qu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取状态 的本地化字符串。
        /// </summary>
        internal static string ReadStatus {
            get {
                return ResourceManager.GetString("ReadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启设备 的本地化字符串。
        /// </summary>
        internal static string RelatedDev {
            get {
                return ResourceManager.GetString("RelatedDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启门口机 的本地化字符串。
        /// </summary>
        internal static string RelatedDoorbell {
            get {
                return ResourceManager.GetString("RelatedDoorbell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 住户 的本地化字符串。
        /// </summary>
        internal static string Resident {
            get {
                return ResourceManager.GetString("Resident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生日 的本地化字符串。
        /// </summary>
        internal static string residentBirth {
            get {
                return ResourceManager.GetString("residentBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性別 的本地化字符串。
        /// </summary>
        internal static string residentGender {
            get {
                return ResourceManager.GetString("residentGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 户主 的本地化字符串。
        /// </summary>
        internal static string residentLeader {
            get {
                return ResourceManager.GetString("residentLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 住户姓名 的本地化字符串。
        /// </summary>
        internal static string residentName {
            get {
                return ResourceManager.GetString("residentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话 的本地化字符串。
        /// </summary>
        internal static string residentPhone {
            get {
                return ResourceManager.GetString("residentPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份证号 的本地化字符串。
        /// </summary>
        internal static string residentPID {
            get {
                return ResourceManager.GetString("residentPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 房间号 的本地化字符串。
        /// </summary>
        internal static string residentRo {
            get {
                return ResourceManager.GetString("residentRo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 房号不存在 的本地化字符串。
        /// </summary>
        internal static string RoNotExist {
            get {
                return ResourceManager.GetString("RoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 屏保升级 的本地化字符串。
        /// </summary>
        internal static string ScreensaverUpgarde {
            get {
                return ResourceManager.GetString("ScreensaverUpgarde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送地址或信息标题不得为空 的本地化字符串。
        /// </summary>
        internal static string SendAddrOrMsgCannotBeNull {
            get {
                return ResourceManager.GetString("SendAddrOrMsgCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        internal static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器 的本地化字符串。
        /// </summary>
        internal static string server {
            get {
                return ResourceManager.GetString("server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 室 的本地化字符串。
        /// </summary>
        internal static string shi {
            get {
                return ResourceManager.GetString("shi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 别墅门口机 的本地化字符串。
        /// </summary>
        internal static string smalldoorbell {
            get {
                return ResourceManager.GetString("smalldoorbell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作人员 的本地化字符串。
        /// </summary>
        internal static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同步完成 的本地化字符串。
        /// </summary>
        internal static string SyncFinish {
            get {
                return ResourceManager.GetString("SyncFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目的地址 的本地化字符串。
        /// </summary>
        internal static string TargetAddr {
            get {
                return ResourceManager.GetString("TargetAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该IP非室内机，管理机或门口机所有！ 的本地化字符串。
        /// </summary>
        internal static string TheIPAddrIsNotBelongToIndoorAdminDoorbell {
            get {
                return ResourceManager.GetString("TheIPAddrIsNotBelongToIndoorAdminDoorbell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时序 的本地化字符串。
        /// </summary>
        internal static string TimeSequence {
            get {
                return ResourceManager.GetString("TimeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 临时卡 的本地化字符串。
        /// </summary>
        internal static string TmpCard {
            get {
                return ResourceManager.GetString("TmpCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未预期错误 的本地化字符串。
        /// </summary>
        internal static string unExpectedError {
            get {
                return ResourceManager.GetString("unExpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单元 的本地化字符串。
        /// </summary>
        internal static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单元门口机 的本地化字符串。
        /// </summary>
        internal static string unitdoorbell {
            get {
                return ResourceManager.GetString("unitdoorbell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未开启设备 的本地化字符串。
        /// </summary>
        internal static string UnrelatedDev {
            get {
                return ResourceManager.GetString("UnrelatedDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升级设备类型 的本地化字符串。
        /// </summary>
        internal static string UpgradeDevType {
            get {
                return ResourceManager.GetString("UpgradeDevType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升级文件路径 的本地化字符串。
        /// </summary>
        internal static string UpgradeFilePath {
            get {
                return ResourceManager.GetString("UpgradeFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升级文件类型 的本地化字符串。
        /// </summary>
        internal static string UpgradeFileType {
            get {
                return ResourceManager.GetString("UpgradeFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传时间 的本地化字符串。
        /// </summary>
        internal static string UploadTime {
            get {
                return ResourceManager.GetString("UploadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不得为空 的本地化字符串。
        /// </summary>
        internal static string UserCannotBeNull {
            get {
                return ResourceManager.GetString("UserCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本号 的本地化字符串。
        /// </summary>
        internal static string VersionNum {
            get {
                return ResourceManager.GetString("VersionNum", resourceCulture);
            }
        }
    }
}
